name: CI

on: push

jobs:

  appinspect-api:
    name: AppInspect API Validation
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
     - run: |
          find . -name '*.pyc' -delete
          tar --exclude="utbox/local" --exclude="utbox/metadata/local.meta" -zcvf utbox.tgz utbox
     - uses: splunk/appinspect-api-action@v2
       with:
        filePath: utbox.tgz
        splunkUser: ${{ secrets.SPLUNK_USER }}
        splunkPassword: ${{ secrets.SPLUNK_PASS }}
        includedTags: cloud
        failOnError: true
        failOnWarning: false

  splunk-test:
    needs: appinspect-api
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["7.3.9","7.2.10.1","8.2"]
    services:
      splunk:
        image: splunk/splunk:${{ matrix.version }}
        env:
          SPLUNK_START_ARGS: --accept-license
          SPLUNK_PASSWORD: password
        options: >-
          --health-interval 30s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 8000:8000
          - 8089:8089

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy app to service container
        run: docker cp utbox ${{ job.services.splunk.id }}:/opt/splunk/etc/apps/utbox

      - run: docker exec -i ${{ job.services.splunk.id }} ls -a /opt/splunk/etc/apps/utbox
      - run: docker exec -i ${{ job.services.splunk.id }} ls -a /opt/splunk/etc/apps

      - name: Restart instance
        run: |
          curl -k -u admin:password https://localhost:8089/services/server/control/restart -X POST
          sleep 30
      - name: Print App Configuration
        run: |
          curl -k -u admin:password https://localhost:8089/services/apps/local/utbox

      - name: Test ut_parse_simple
        run:
          curl -k -u admin:password https://localhost:8089/services/search/jobs/export -d search="|makeresults n = 1 | eval cs_url = \"https://splunk.com\", list = \"*\" |  \`ut_parse_simple(cs_url)\`" -d output_mode=json | jq -e '(.result.ut_scheme | contains("https"))'
      
      - name: Test ut_parse_extended
        run:
          curl -k -u admin:password https://localhost:8089/services/search/jobs/export -d search="|makeresults n = 1 | eval cs_url = \"https://splunk.com/test\", list = \"*\" |  \`ut_parse_extended(cs_url, list)\`" -d output_mode=json | jq -e '(.result.ut_path | contains("test"))'
